apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "cluster-queue"
spec:
  namespaceSelector: {}  # match all.
  resourceGroups:
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: "default-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 8
      - name: "memory"
        nominalQuota: 64Gi
      - name: "nvidia.com/gpu"
        nominalQuota: 0
## Default example covering generic nvidia gpus
#   - coveredResources: ["cpu", "memory", "nvidia.com/gpu"]
#     flavors:
#     - name: "default-flavor"
#       resources:
#       - name: "cpu"
#         nominalQuota: 9
#       - name: "memory"
#         nominalQuota: 36Gi
#       - name: "nvidia.com/gpu"
#         nominalQuota: 5